spring:
  application:
    name: demo1-provider # spring 应用名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: c2c92c4a-2e93-4e24-925b-cc537eafac1a
server:
  port: 18082 # 服务器端口。默认为 8080
