spring:
  application:
    name: demo-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# dubbo 配置项
dubbo:
  registry:
    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
  cloud:
    subscribed-services: '*' # 设置订阅的应用列表，默认为 * 订阅所有应用。

server:
  port: 18085
